Repository TokTok/debugtox, pull requests merged in 2025-02, with the labels that each got.

#8 cleanup: Give debugtox netlify deployment an index.html.
  BUILD.bazel
  platform/wasm/netlify.sh
  platform/wasm/wasm.Dockerfile
  platform/wasm/wasm.Dockerfile.dockerignore
Labels: cleanup

#10 docs: Update link from render to netlify.
  README.md
Labels: documentation

#11 chore: Add reusable workflow for release builds.
  .clang-format
  .github/workflows/build-test-deploy.yml
  .gitignore
  .restyled.yaml
  CMakeLists.txt
  CMakePresets.json
  cmake/Installation.cmake
  platform/android/cross-compile/build.sh
  platform/android/keystore.jks
  platform/android/qt-6.2.4/AndroidManifest.xml
  platform/android/qt-6.8.1/AndroidManifest.xml
  platform/appimage/build.sh
  platform/deps.depfile
  platform/flatpak/build.sh
  platform/flatpak/chat.tox.DebugTox.json
  platform/linux/chat.tox.DebugTox.appdata.xml
  platform/linux/chat.tox.DebugTox.desktop
  platform/macos/Brewfile-static
  platform/macos/Info.plist
  platform/macos/backgroundImage.tiff
  platform/macos/build.sh
  platform/macos/createdmg
  platform/macos/gplv3.rtf
  platform/wasm/wasm.Dockerfile
  platform/wasm/wasm.Dockerfile.dockerignore
  platform/windows/cross-compile/README.md
  platform/windows/cross-compile/build.sh
  platform/windows/cross-compile/check-dlls
  platform/windows/cross-compile/dll-deps
  platform/windows/debugtox.ico
  platform/windows/debugtox.rc
  platform/windows/debugtox64.nsi
  platform/windows/generate-icon.sh
  resources/images/icons/128x128/debugtox.png
  resources/images/icons/14x14/debugtox.png
  resources/images/icons/16x16/debugtox.png
  resources/images/icons/192x192/debugtox.png
  resources/images/icons/22x22/debugtox.png
  resources/images/icons/24x24/debugtox.png
  resources/images/icons/256x256/debugtox.png
  resources/images/icons/32x32/debugtox.png
  resources/images/icons/36x36/debugtox.png
  resources/images/icons/48x48/debugtox.png
  resources/images/icons/512x512/debugtox.png
  resources/images/icons/64x64/debugtox.png
  resources/images/icons/72x72/debugtox.png
  resources/images/icons/96x96/debugtox.png
  resources/images/icons/debugtox.icns
  resources/images/icons/debugtox.svg
  src/main.cpp
  test/smoke-test.sh
  third_party/.gitignore
Labels: packaging, chore

#12 chore: Add clog configuration for changelog generation.
  .clog.toml
  CHANGELOG.md
Labels: chore

#14 chore: Add release issue template and workflow.
  .github/ISSUE_TEMPLATE/release.yml
  .github/workflows/draft.yml
  .github/workflows/release.yml
  .reviewable/completion.js
  .reviewable/settings.yaml
  CHANGELOG.md
Labels: chore

#16 chore: Release v0.0.1
  CHANGELOG.md
Labels: chore

#19 cleanup: Use tools from ci-tools instead of local copies.
  cmake/Installation.cmake
  platform/android/cross-compile/build.sh
  platform/android/keystore.jks
  platform/appimage/build.sh
  platform/flatpak/build.sh
  platform/macos/build.sh
  platform/macos/createdmg
  platform/macos/gplv3.rtf
  platform/windows/cross-compile/README.md
  platform/windows/cross-compile/build.sh
  platform/windows/cross-compile/check-dlls
  platform/windows/cross-compile/dll-deps
  platform/windows/generate-icon.sh
Labels: cleanup

#21 chore: Release v0.0.2-rc.1
  CHANGELOG.md
Labels: chore
